### ISSUE TITLE
TTD fails due to file encryption

### ISSUE THREAD

**Issue by ssylvan** [microsoft/WinDbg-Feedback#13]
Trying to launch TTD fails instantly. It seems to have something to do with encryption, and indeed TTD.exe is encrypted. 

However, since windows (or the store?) apparently has chosen to encrypt this file, it seems like WinDBG needs to deal with that reality (if it can't for some fundamental reason, it should disable encryption for those files or at least tell the user how to do it.. simply right clicking and unchecking encryption does not work for thees files, you get access denied)... 

So while I don't know why encryption is enabled (I have done nothing to enable it myself.. it's not a corp managed machine, bitlocker isn't on, etc.), that is the state it's in so apparently it's a configuration windows can end up with. So I guess this is a thing that WinDBG has to deal with (other apps seem to do it).

Here's a log:

2019-01-22:18:49:22:686 : Information : DbgX.Shell.exe : OS Version: Windows 10 Pro (10.0.17763) (64-bit)
2019-01-22:18:49:22:717 : Warning : DbgX.Services.dll : Property CommandWindowSettings.CopyWithFormatting not found.
2019-01-22:18:49:22:766 : Information : DbgX.Shell.exe : Version: 1.0.1812.12001
2019-01-22:18:49:22:816 : Information : DbgX.Debugger.dll : Environment variable _NT_SYMBOL_PATH == .;srv*C:\SymCache*http://msdl.microsoft.com/download/symbols
2019-01-22:18:49:22:906 : Information : DbgX.Shell.exe : Command line: "C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\DbgX.Shell.exe" 
2019-01-22:18:49:22:816 : Information : DbgX.Debugger.dll : Starting EngHost: C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64 npipe:pipe=DbgX_2583b318a3074c609268b46ae9044949,password=7630da5ba04c "C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64"
2019-01-22:18:49:22:856 : Information : DbgX.dll : (E) Added process EngHost (11372) to job object 6b54e033-6762-43e9-a7f3-74808edad090
2019-01-22:18:49:23:086 : Information : DbgX.dll : (E) Changed client, isPrimaryClient=True
2019-01-22:18:49:23:086 : Information : DbgX.dll : (E) Executing secondary thread request: ChangeClientRequest
2019-01-22:18:49:23:696 : Information : DbgX.Debugger.dll : Code level changed to Assembly
2019-01-22:18:49:23:096 : Information : DbgX.dll : (E) Completed secondary thread request: ChangeClientRequest
2019-01-22:18:49:23:696 : Information : DbgX.Debugger.dll : Code level changed to Source
2019-01-22:18:49:23:096 : Information : DbgX.dll : (E) Executing request: AppendSymbolPathWide: .;srv*C:\SymCache*http://msdl.microsoft.com/download/symbols
2019-01-22:18:49:23:096 : Information : DbgX.dll : (E) Completed request (1 ms) : AppendSymbolPathWide: .;srv*C:\SymCache*http://msdl.microsoft.com/download/symbols
2019-01-22:18:49:23:096 : Information : DbgX.dll : (E) Refreshing because we're in a break state.
2019-01-22:18:49:23:706 : Information : DbgX.Debugger.dll : (E) Notifying refresh requested
2019-01-22:18:49:23:096 : Information : DbgX.dll : (E) Executing request: ScriptProvidersRequest
2019-01-22:18:49:23:106 : Information : DbgX.dll : (E) Completed request (6 ms) : ScriptProvidersRequest
2019-01-22:18:49:23:411 : Information : DbgX.dll : (E) Executing request: ModelQueryRequest: Debugger
2019-01-22:18:49:23:411 : Information : DbgX.dll : (E) Completed request (1 ms) : ModelQueryRequest: Debugger
2019-01-22:18:49:23:418 : Information : DbgX.dll : (E) Executing request: ModelQueryRequest: Debugger.Utility.Objects.Aggregate(@$curframe.LocalVariables, @$curframe.Parameters)
2019-01-22:18:49:23:418 : Information : DbgX.dll : (E) Completed request (0 ms) : ModelQueryRequest: Debugger.Utility.Objects.Aggregate(@$curframe.LocalVariables, @$curframe.Parameters)
2019-01-22:18:49:23:711 : Information : DbgX.dll : (E) Executing request: ScriptProvidersRequest
2019-01-22:18:49:23:711 : Information : DbgX.dll : (E) Completed request (0 ms) : ScriptProvidersRequest
2019-01-22:18:49:23:716 : Information : DbgX.dll : (E) Executing request: GetSymbolPathRequest
2019-01-22:18:49:23:746 : Information : DbgX.Debugger.dll : Symbol path changed: .;srv*C:\SymCache*http://msdl.microsoft.com/download/symbols
2019-01-22:18:49:23:719 : Information : DbgX.dll : (E) Completed request (1 ms) : GetSymbolPathRequest
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe : Total startup time: 1914 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Process startup' time: 164 ms, started at 0 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Create main window' time: 250 ms, started at 254 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Composition catalog' time: 371 ms, started at 294 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Merging resource dictionaries' time: 59 ms, started at 509 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Compose components' time: 116 ms, started at 664 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Setting main window viewmodel' time: 120 ms, started at 814 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Startup listeners' time: 92 ms, started at 934 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'ViewManager initialization' time: 256 ms, started at 1044 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Main window show' time: 611 ms, started at 1304 ms
2019-01-22:18:49:23:796 : Information : DbgX.Shell.exe :     Phase 'Shell startup listeners' time: 0 ms, started at 1814 ms
2019-01-22:18:49:26:929 : Information : DbgX.dll : (E) Executing request: GetProcessListRequest
2019-01-22:18:49:26:973 : Warning : DbgX.dll : (E) FAILURE HR=0xFFFFFFFF: GetRunningProcessDescriptionWide for PID 120 failed.
2019-01-22:18:49:27:442 : Information : DbgX.dll : (E) Completed request (513 ms) : GetProcessListRequest
2019-01-22:18:49:39:274 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTD.exe into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTD.exe
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:301 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDAnalyze.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDAnalyze.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:327 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TtdExt.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TtdExt.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:356 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDInject.exe into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDInject.exe
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:379 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDLoader.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDLoader.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:405 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDRecord.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDRecord.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:441 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDRecordCPU.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDRecordCPU.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:469 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDReplay.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDReplay.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:497 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDReplayCPU.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDReplayCPU.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:531 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\TTDWriter.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTDWriter.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:558 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\Analyzers\HeapAnalysis.js into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\Analyzers\HeapAnalysis.js
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:579 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\Analyzers\Resources.json into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\Analyzers\Resources.json
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:605 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\Analyzers\TtdAnalyze.js into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\Analyzers\TtdAnalyze.js
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:635 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTD.exe into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTD.exe
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:667 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDAnalyze.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDAnalyze.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:696 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TtdExt.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TtdExt.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:727 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDInject.exe into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDInject.exe
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:752 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDLoader.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDLoader.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:778 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDLoaderWow64.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDLoaderWow64.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:808 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDRecord.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDRecord.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:848 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDRecordCPU.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDRecordCPU.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:879 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDReplay.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDReplay.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:915 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDReplayCPU.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDReplayCPU.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:951 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\TTDWriter.dll into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\TTDWriter.dll
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:973 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\Analyzers\HeapAnalysis.js into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\Analyzers\HeapAnalysis.js
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:39:995 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\Analyzers\Resources.json into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\Analyzers\Resources.json
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:40:017 : Error : DbgX.External.dll : Failed to copy file C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1812.12001.0_neutral__8wekyb3d8bbwe\amd64\TTD\wow64\Analyzers\TtdAnalyze.js into file C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\wow64\Analyzers\TtdAnalyze.js
 With exception: 
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DbgX.Microsoft.TimeTravel.ExternalTimeTravelRecordingCustomization.CopyDirectoryRecursive(String destPath, String srcPath)
2019-01-22:18:49:40:019 : Information : DbgXUI.dll : TTD cmd exe: C:\ProgramData\Microsoft\Windbg\1-1812-12001\TTD\TTD.exe
2019-01-22:18:49:40:019 : Information : DbgXUI.dll : TTD cmd args:  -out "F:\OneDrive\Documents" -attach 9956
2019-01-22:18:49:40:020 : Error : DbgXUI.dll : 
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at DbgXUI.Services.TtdRecordSessionInfo.StartRecording()
   at DbgXUI.Services.TtdRecordingService.AttachToProcessAndOpenTrace(UInt32 pid, String processName, TtdRecordOptions recordOptions)
   at DbgXUI.Dialogs.AttachViewModel.DoAttachToRecord(RunningProcess process)
2019-01-22:18:49:40:023 : Information : DbgX.Services.dll : Action item published: Error - Could not attach to process under the Time Travel Debugging: The system cannot find the file specified

**Comment by lzybkr** [comment]
I'm going through old issues and this one seems like it was likely fixed.
