### ISSUE TITLE
Dock Debugger Window throws System.InvalidOperationException

### ISSUE THREAD

**Issue by vcmcstech** [microsoft/WinDbg-Feedback#74]
I startup WinDbg Preview 1.2202.7001.0 on win 10 pro.  Debugger is undocked.  I click Dock and Windbg crashes.  Error below found in event viewer

```
Application: DbgX.Shell.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewSite.OnChildrenChanged(System.Object, System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(System.Object, System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertItem(Int32, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.OwnershipCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertItem(Int32, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.DockOperations.AddLocationBookmark(Microsoft.VisualStudio.PlatformUI.Shell.ViewElement)
   at Microsoft.VisualStudio.PlatformUI.Shell.DockOperations.SnapToBookmark(Microsoft.VisualStudio.PlatformUI.Shell.View, Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile, Microsoft.VisualStudio.PlatformUI.Shell.ViewBookmarkType, System.Action`3<Microsoft.VisualStudio.PlatformUI.Shell.View,Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile,Microsoft.VisualStudio.PlatformUI.Shell.ViewBookmarkType>)
   at Microsoft.VisualStudio.PlatformUI.Shell.DockOperations.SnapToBookmark(Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup, Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile, Microsoft.VisualStudio.PlatformUI.Shell.ViewBookmarkType, System.Action`3<Microsoft.VisualStudio.PlatformUI.Shell.View,Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile,Microsoft.VisualStudio.PlatformUI.Shell.ViewBookmarkType>)
   at Microsoft.VisualStudio.PlatformUI.Shell.DockOperations.SnapToBookmark(Microsoft.VisualStudio.PlatformUI.Shell.ViewElement)
   at System.Windows.Input.CommandBinding.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(System.Object, System.Windows.Input.ExecutedRoutedEventArgs, System.Windows.Input.CommandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(System.Object, System.Windows.IInputElement, Boolean)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DbgX.Shell.Program.Main()


```

**Comment by MV10** [comment]
I get the same error just launching the app (the window never appears). On another machine it works normally. Both are running 20H2 build 19042.1586. (These were both installed by downloading and unzipping since the machines are blocked from accessing the store.)

This line in the error log seems somewhat suspicious: `Framework Version: v4.0.30319`

**Comment by emmasab** [comment]
Hi, this seems related to the .NET version. We recently updated WinDbg Preview to use .NET 6, could you check if this repros after getting the latest store version?

**Comment by KenSykes** [comment]
We are cleaning up the issues list. This bug is older than six months. If you still see this issue in the current debugger and would like to see a fix please submit a new report.\ Thanks!
