### ISSUE TITLE
Win32 error 0n87

### ISSUE THREAD

**Issue by aleff-github** [microsoft/WinDbg-Feedback#98]
I have installed WinDbg and I'm trying to open an ELF Dump file having the following error
```
************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : false
   AllowNugetExeUpdate : false

   - Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true


************* Waiting for Debugger Extensions Gallery to Initialize **************
.
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 36

Microsoft (R) Windows Debugger Version 10.0.25324.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:/Users/User/Dumps/mem.elf]
Could not match Dump File signature - invalid file format
Could not open dump file [C:/Users/User/Dumps/mem.elf], Win32 error 0n87
    "Parametro non corretto."
```

knowing that the image have the following features:
```
Suggested Profile(s) : Win7SP1x64, Win7SP0x64, Win2008R2SP0x64, Win2008R2SP1x64_23418, Win2008R2SP1x64, Win7SP1x64_23418
AS Layer1 : WindowsAMD64PagedMemory (Kernel AS)
AS Layer2 : VirtualBoxCoreDumpElf64 (Unnamed AS)
AS Layer3 : FileAddressSpace (/home/user/dumps/mem_dumps/01/mem.elf)
```

This is the log about the op:
```
2023-04-28:09:20:16:511 : Information : DbgX.Services.dll : Process arch: IMAGE_FILE_MACHINE_UNKNOWN, Native arch: IMAGE_FILE_MACHINE_AMD64
2023-04-28:09:20:21:543 : Information : DbgX.dll : (E) Executing request: OpenDumpFileRequest: Dump File 'C:/Users/User/Dumps/mem.elf'
2023-04-28:09:20:21:554 : Information : DbgX.Debugger.dll : Starting EngHost: C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2303.30001.0_x64__8wekyb3d8bbwe\amd64\EngHost.exe npipe:pipe=DbgX_d4947e0a263145108251bfcad79330bf,password=50cbdc789258 "C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2303.30001.0_x64__8wekyb3d8bbwe\amd64" "C:\ProgramData\Dbg"
2023-04-28:09:20:21:562 : Information : DbgX.dll : (E) Added process EngHost (15676) to job object 776cb9fb-afcf-4dda-babc-65952a5f97b9
2023-04-28:09:20:21:765 : Information : DbgX.dll : (E) DebugConnect returned S_OK
2023-04-28:09:20:21:768 : Information : DbgX.dll : (E) Killing process EngHost (7800) for job object c90fce22-3818-473f-ab5b-7d33807bfed2 (HasExited: False)
2023-04-28:09:20:21:768 : Information : DbgX.dll : (E) Changed client, isPrimaryClient=True
2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Code level changed to SOURCE
2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Executing secondary thread request: ChangeClientRequest
2023-04-28:09:20:21:769 : Warning : DbgX.Debugger.dll : (E) Failed to set parent hWnd to the new engine.
2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Symbol path = '', source path = '' (Checking for client refresh)
2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : ServiceManager : Service '{507c628c-ddc3-4829-91af-01e1bf541b7b}' added to the service container
2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : ServiceManager : Service '{91d9084f-a8ac-4d4f-88e1-5e65e8a64c60}' added to the service container
2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : Verbose : ELFBin : Checking for ELF signature
2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : File header does not match ELF signature.  Not processing as an ELF file
2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : Checking for KDump signature
2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : File header does not match KDump signature.  Not processing as a KDump file
2023-04-28:09:20:23:885 : Information : DbgX.dll : (E) Completed request (2342 ms) : OpenDumpFileRequest: Dump File 'C:/Users/User/Dumps/mem.elf'
2023-04-28:09:20:23:886 : Information : DbgX.Services.dll : Action item published: Error - The debugging session could not be started: FAILURE HR=0x80070057: Failed to OpenDumpFileWide
2023-04-28:09:20:23:887 : Information : DbgX.dll : (E) Completed secondary thread request: ChangeClientRequest
2023-04-28:09:20:28:781 : Error : DbgX.Services.dll : WindowsDebugger.WindowsDebuggerException: FAILURE HR=0x80070057: Failed to OpenDumpFileWide
   at WindowsDebugger.DbgEng.HRESULTExtensions.ThrowOnFailed(HRESULT hr, String operation)
   at DbgX.Requests.Initialization.OpenDumpFileRequest.DbgX.Requests.Initialization.IDumpFileRequest.OpenDumpFile(EngineInterfaces engine, ProcessorArchitecture targetArchitecture)
   at DbgX.Requests.Initialization.OpenDumpFileRequestBase.DoInitializeEngine(IEngineRequestServices ers, EngineInterfaces engine)
   at DbgX.Requests.Initialization.InitializationRequest.DoExecute(IEngineRequestServices ers, EngineInterfaces engine)
   at DbgX.Requests.EngineRequestWithTask`1.Execute(IEngineRequestServices ers, EngineInterfaces engine)
--- End of stack trace from previous location ---
   at DbgX.Debugger.Services.TargetInitializationService.OpenDumpFileAsync(String dumpFile, EngineOptions engOpt)
   at DbgX.Debugger.TargetOptions.OpenDumpHandler.ProcessLaunchOptionAsync(OpenDumpOption option, EngineOptions engineOptions)
   at DbgX.Debugger.TargetOptions.LaunchTargetOptionHandler`1.ProcessOptionAsync(T option, EngineOptions engineOptions)
   at DbgX.Services.CommandLine.ConfiguredTargetManager.LaunchTargetAsync(IDbgTargetConfiguration target)

```

**Comment by 62f** [comment]
<details> I have installed WinDbg and I'm trying to open an ELF Dump file having the following error
> 
> ```
> ************* Preparing the environment for Debugger Extensions Gallery repositories **************
>    ExtensionRepository : Implicit
>    UseExperimentalFeatureForNugetShare : false
>    AllowNugetExeUpdate : false
> 
>    - Configuring repositories
>       ----> Repository : LocalInstalled, Enabled: true
>       ----> Repository : UserExtensions, Enabled: true
> 
> 
> ************* Waiting for Debugger Extensions Gallery to Initialize **************
> .
>    ----> Repository : UserExtensions, Enabled: true, Packages count: 0
>    ----> Repository : LocalInstalled, Enabled: true, Packages count: 36
> 
> Microsoft (R) Windows Debugger Version 10.0.25324.1001 AMD64
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> 
> Loading Dump File [C:/Users/User/Dumps/mem.elf]
> Could not match Dump File signature - invalid file format
> Could not open dump file [C:/Users/User/Dumps/mem.elf], Win32 error 0n87
>     "Parametro non corretto."
> ```
> 
> knowing that the image have the following features:
> 
> ```
> Suggested Profile(s) : Win7SP1x64, Win7SP0x64, Win2008R2SP0x64, Win2008R2SP1x64_23418, Win2008R2SP1x64, Win7SP1x64_23418
> AS Layer1 : WindowsAMD64PagedMemory (Kernel AS)
> AS Layer2 : VirtualBoxCoreDumpElf64 (Unnamed AS)
> AS Layer3 : FileAddressSpace (/home/user/dumps/mem_dumps/01/mem.elf)
> ```
> 
> This is the log about the op:
> 
> ```
> 2023-04-28:09:20:16:511 : Information : DbgX.Services.dll : Process arch: IMAGE_FILE_MACHINE_UNKNOWN, Native arch: IMAGE_FILE_MACHINE_AMD64
> 2023-04-28:09:20:21:543 : Information : DbgX.dll : (E) Executing request: OpenDumpFileRequest: Dump File 'C:/Users/User/Dumps/mem.elf'
> 2023-04-28:09:20:21:554 : Information : DbgX.Debugger.dll : Starting EngHost: C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2303.30001.0_x64__8wekyb3d8bbwe\amd64\EngHost.exe npipe:pipe=DbgX_d4947e0a263145108251bfcad79330bf,password=50cbdc789258 "C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2303.30001.0_x64__8wekyb3d8bbwe\amd64" "C:\ProgramData\Dbg"
> 2023-04-28:09:20:21:562 : Information : DbgX.dll : (E) Added process EngHost (15676) to job object 776cb9fb-afcf-4dda-babc-65952a5f97b9
> 2023-04-28:09:20:21:765 : Information : DbgX.dll : (E) DebugConnect returned S_OK
> 2023-04-28:09:20:21:768 : Information : DbgX.dll : (E) Killing process EngHost (7800) for job object c90fce22-3818-473f-ab5b-7d33807bfed2 (HasExited: False)
> 2023-04-28:09:20:21:768 : Information : DbgX.dll : (E) Changed client, isPrimaryClient=True
> 2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Code level changed to SOURCE
> 2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Executing secondary thread request: ChangeClientRequest
> 2023-04-28:09:20:21:769 : Warning : DbgX.Debugger.dll : (E) Failed to set parent hWnd to the new engine.
> 2023-04-28:09:20:21:769 : Information : DbgX.dll : (E) Symbol path = '', source path = '' (Checking for client refresh)
> 2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : ServiceManager : Service '{507c628c-ddc3-4829-91af-01e1bf541b7b}' added to the service container
> 2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : ServiceManager : Service '{91d9084f-a8ac-4d4f-88e1-5e65e8a64c60}' added to the service container
> 2023-04-28:09:20:22:284 : Information : DbgX.Services.dll : Verbose : ELFBin : Checking for ELF signature
> 2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : File header does not match ELF signature.  Not processing as an ELF file
> 2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : Checking for KDump signature
> 2023-04-28:09:20:22:285 : Information : DbgX.Services.dll : Verbose : ELFBin : File header does not match KDump signature.  Not processing as a KDump file
> 2023-04-28:09:20:23:885 : Information : DbgX.dll : (E) Completed request (2342 ms) : OpenDumpFileRequest: Dump File 'C:/Users/User/Dumps/mem.elf'
> 2023-04-28:09:20:23:886 : Information : DbgX.Services.dll : Action item published: Error - The debugging session could not be started: FAILURE HR=0x80070057: Failed to OpenDumpFileWide
> 2023-04-28:09:20:23:887 : Information : DbgX.dll : (E) Completed secondary thread request: ChangeClientRequest
> 2023-04-28:09:20:28:781 : Error : DbgX.Services.dll : WindowsDebugger.WindowsDebuggerException: FAILURE HR=0x80070057: Failed to OpenDumpFileWide
>    at WindowsDebugger.DbgEng.HRESULTExtensions.ThrowOnFailed(HRESULT hr, String operation)
>    at DbgX.Requests.Initialization.OpenDumpFileRequest.DbgX.Requests.Initialization.IDumpFileRequest.OpenDumpFile(EngineInterfaces engine, ProcessorArchitecture targetArchitecture)
>    at DbgX.Requests.Initialization.OpenDumpFileRequestBase.DoInitializeEngine(IEngineRequestServices ers, EngineInterfaces engine)
>    at DbgX.Requests.Initialization.InitializationRequest.DoExecute(IEngineRequestServices ers, EngineInterfaces engine)
>    at DbgX.Requests.EngineRequestWithTask`1.Execute(IEngineRequestServices ers, EngineInterfaces engine)
> --- End of stack trace from previous location ---
>    at DbgX.Debugger.Services.TargetInitializationService.OpenDumpFileAsync(String dumpFile, EngineOptions engOpt)
>    at DbgX.Debugger.TargetOptions.OpenDumpHandler.ProcessLaunchOptionAsync(OpenDumpOption option, EngineOptions engineOptions)
>    at DbgX.Debugger.TargetOptions.LaunchTargetOptionHandler`1.ProcessOptionAsync(T option, EngineOptions engineOptions)
>    at DbgX.Services.CommandLine.ConfiguredTargetManager.LaunchTargetAsync(IDbgTargetConfiguration target)
> ```</details>
The .dmp file's parent directory security needs file permissions to be made inheritable from the root directory on the new drive. Chances are that you xcopy /o'd the child folder into its current location from another drive and the subdirectory is looking upstream to the new home for its security instructions to let the file contents be shown, not just the file name. Try opening the .dmp file yourself with a text editor and it'll look like a bunch of blank paragraphs instead of crash data until you get the directory permissions sorted.

**Comment by KenSykes** [comment]
We are cleaning up the issues list. This bug is older than six months. If you still see this issue in the current debugger and would like to see a fix please submit a new report.\ Thanks!
